src/routes/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session, jsonify
from src.database import db_session
import src.models as models
from datetime import datetime
import datetime
import time
import threading
import copy
from argon2 import PasswordHasher
import logging
from sqlalchemy import desc
from src.users import verification_mail
import flask_jwt_extended
import json 

ph = PasswordHasher(hash_len=64, salt_len=32)

view = Blueprint("view", __name__)

@view.route("/checkout")
@flask_jwt_extended.jwt_required
def checkout():
    pass
    return render_template("checkout.html")

@view.route("/checkout/address")
@flask_jwt_extended.jwt_required
def delivery_address():
    user_id = flask_jwt_extended.get_jwt_identity()
    address_count = db_session.query(models.UserAddress).filter(models.UserAddress.user_id == user_id).count()
    return render_template("checkout.html", address_count=address_count + 1)

@view.route("/edit_address/<address_id>")
@flask_jwt_extended.jwt_required
def edit_address(address_id):
    address = db_session.query(models.UserAddress).filter(models.UserAddress.id == int(address_id)).one_or_none()
    return render_template("edit_address.html", address=address)

@view.route("/edit_delivery_address", methods=["GET", "POST"])
@flask_jwt_extended.jwt_required
def edit_delivery_address():
    address_id = request.form["address_id"]
    address = db_session.query(models.UserAddress).filter(models.UserAddress.id == int(address_id)).one_or_none()
    address.address_name = request.form["address_name"]
    address.first_name = request.form["first_name"]
    address.last_name = request.form["last_name"]
    address.email = request.form["email"]
    address.phone_number = request.form["phone_number"]
    address.address = request.form["address"]
    address.country = request.form["country"]
    address.state = request.form["state"]
    address.city = request.form["city"]
    address.postal_code = request.form["postal_code"]

    try:
        db_session.commit()
    except Exception as e:
        print(e)
        db_session.rollback()
        return redirect(url_for("view.checkout"))
        
    return redirect(url_for("view.cart"))

@view.route("/add_address", methods=["GET", "POST"])
@flask_jwt_extended.jwt_required
def add_address():
    try:
        user_id = flask_jwt_extended.get_jwt_identity()
        address_name = request.form["address_name"]
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        email = request.form["email"]
        phone_number = request.form["phone_number"]
        address = request.form["address"]
        country = request.form["country"]
        state = request.form["state"]
        city = request.form["city"]
        postal_code = request.form["postal_code"]
        
        add_address = models.UserAddress(
            address_name=address_name,
            user_id=user_id,
            first_name=first_name,
            last_name=last_name,
            email=email,
            phone_number=phone_number,
            address=address,
            country=country,
            state=state,
            city=city,
            postal_code=postal_code
        )
        db_session.add(add_address)
        db_session.flush()
    except Exception as e:
        print(e)
        return redirect(url_for("view.checkout"))

    try:
        db_session.commit()
        address_id = add_address.id
    except Exception as e:
        print(e)
        db_session.rollback()
        return redirect(url_for("view.checkout"))
        
    return redirect(url_for("view.cart"))

@view.route("/orders")
@flask_jwt_extended.jwt_required
def orders():
    user_id = flask_jwt_extended.get_jwt_identity()
    cart_list = db_session.query(models.Orders, models.Product, models.ProductImages).filter(models.Orders.product_id == models.Product.id).filter(models.Orders.user_id == user_id).filter(models.ProductImages.product_id == models.Orders.product_id, models.ProductImages.profile_img == True).all()
    return render_template("orders.html", cart_list=cart_list)

@view.route("/place_order", methods=["GET", "POST"])
@flask_jwt_extended.jwt_required
def place_order():
    user_id = flask_jwt_extended.get_jwt_identity()
    cart_list = db_session.query(models.Cart).filter(models.Cart.user_id == user_id).all()
    try:
        address_id = request.form["address"]
        created_at = datetime.datetime.now()
        for cart in cart_list:
            create_order = models.Orders(
                order_id=address_id,
                user_id=user_id,
                product_id=cart.product_id,
                status='pending',
                created_at=created_at,
            )
            db_session.add(create_order)
            db_session.flush()
    except Exception as e:
        print(e)
        return redirect(url_for("view.cart"))

    try:
        db_session.commit()
    except Exception as e:
        print(e)
        db_session.rollback()
        return redirect(url_for("view.cart"))

    return redirect(url_for("view.orders"))

@view.route("/upi")
@flask_jwt_extended.jwt_required
def upi():
    pass
    return render_template("upi.html")

@view.route("/payment_card", methods=["GET", "POST"])
@flask_jwt_extended.jwt_required
def payment_card():
    print(request.form)
    return redirect(url_for("view.cart"))

@view.route("/payment")
@flask_jwt_extended.jwt_required
def payment():
    pass
    return render_template("payment.html")

@view.route("/buynow", methods=["GET", "POST"])
@flask_jwt_extended.jwt_required
def buynow():
    print(request.form)
    return redirect(url_for("view.products"))

@view.route("/cart")
@flask_jwt_extended.jwt_required
def cart():
    user_id = flask_jwt_extended.get_jwt_identity()
    cart_list = db_session.query(models.Cart, models.Product, models.ProductImages).filter(models.Cart.product_id == models.Product.id).filter(models.Cart.user_id == user_id).filter(models.ProductImages.product_id == models.Cart.product_id, models.ProductImages.profile_img == True).all()
    address = db_session.query(models.UserAddress).filter(models.UserAddress.user_id == user_id).all()
    total = 0
    for cart in cart_list:
        total += int(cart[1].price)

    print(total)
    data =[]
    for add in address:
        data.append({
        "address_id": add.id,
        "address_name": add.address_name,
        "first_name": add.first_name,
        "last_name": add.last_name,
        "email": add.email,
        "phone_number": add.phone_number,
        "address": add.address,
        "country": add.country,
        "state": add.state,
        "city": add.city,
        "postal_code": add.postal_code
        })


    data =  json.dumps(data)
    return render_template("cart.html", cart_list=cart_list, cart_count=len(cart_list), total=total, address=address, data=data)

@view.route("/add_to_cart/<product_id>")
@flask_jwt_extended.jwt_required
def add_to_cart(product_id):
    user_id = flask_jwt_extended.get_jwt_identity()
    try:
        if product_id != "0":
            add_to_cart = models.Cart(user_id=user_id, product_id=product_id)
            db_session.add(add_to_cart)
            db_session.flush()
            db_session.commit()
    except Exception as e:
        print(e)

    return redirect(url_for("view.cart"))


@view.route("/cart_remove/<int:cart_id>")
@flask_jwt_extended.jwt_required
def cart_remove(cart_id):
    try:
        cart_item = db_session.query(models.Cart).filter(models.Cart.id == cart_id).one_or_none()
        db_session.delete(cart_item)
        db_session.commit()
    except Exception as e:
        print(e)

    return redirect(url_for("view.cart"))

@view.route("/product/<id>")
@flask_jwt_extended.jwt_required
def product(id):
    try:
        user_id = flask_jwt_extended.get_jwt_identity()
        product = db_session.query(models.Product).filter(models.Product.id == id).one_or_none()
        product_images = db_session.query(models.ProductImages).filter(models.ProductImages.product_id == id).all()
        category_name = db_session.query(models.Category.name).filter(models.Category.id == product.category_id).one_or_none()
        cart_count = db_session.query(models.Cart, models.Product).filter(models.Cart.product_id == models.Product.id).filter(models.Cart.user_id == user_id).count()
    except Exception as e:
        print(e)

    return render_template("shop-single-product.html", product=product, product_images=product_images, category_name=category_name[0], cart_count=cart_count)

@view.route("/products")
@flask_jwt_extended.jwt_required
def products():
    try:
        user_id = flask_jwt_extended.get_jwt_identity()
        is_login = session.get("logged_in")
        products = db_session.query(models.Product, models.ProductImages).filter(models.Product.id == models.ProductImages.product_id, models.ProductImages.profile_img == True).all()
        categories = db_session.query(models.Category).all()
        cart_count = db_session.query(models.Cart, models.Product).filter(models.Cart.product_id == models.Product.id).filter(models.Cart.user_id == user_id).count()
    except Exception as e:
        print(e)

    return render_template("shop-right-sidebar.html", is_login=is_login,products=products,categories=categories, cart_count=cart_count)

@view.route("/products/<int:category_id>")
@flask_jwt_extended.jwt_required
def products_by_category(category_id):
    try:
        user_id = flask_jwt_extended.get_jwt_identity()
        is_login = session.get("logged_in")
        products = db_session.query(models.Product, models.ProductImages).filter(models.Product.id == models.ProductImages.product_id, models.Product.category_id == category_id, models.ProductImages.profile_img == True).order_by(desc(models.Product.id)).all()
        categories = db_session.query(models.Category).all()

src/templates/cart.html
{% extends "layout.html" %}

{% block content %}

  <div class="container single-product-content bg-color-white pt-15px pb-20px">
      <div class="row">
          <div class="col-lg-12">

              <ul class="product-images-gallery">
                
                {% for cart in cart_list %}
                  <li class="cart-list-item">
                      <div class="d-flex item-detail">
                        <a href="{{ url_for('view.product', id=cart[1].id) }}">
                          <img src="{{ url_for('static', filename='assets/images/products/') }}{{ cart[2].image_url }}" 
                          alt="Product image" width="150" height="150">
                        </a>
                          <div class="single-product-des pt-0">
                              <h5 class="product-title pb-0">{{ cart[1].name }}</h5>
                              <div class="quantity d-flex m-0" style="align-items: center;">
                                  <input type="number" step="1" min="1" name="quantity" value="1" title="Qty" class="input-text qty text total-quantity" size="2">
                                  <div class="ml-15px mb-0 single-product-price"><span>₹</span> <strong id="product_price">{{ cart[1].price }}</strong></div>
                              </div>
                          </div>
                          <a href="{{ url_for('view.cart_remove',cart_id=cart[0].id) }}"><i class="fa fa-trash-alt fa-lg" style="color:red; size: 20px;" aria-hidden="true"></i></a>
                      </div>
                      <div class="separator-line"></div>
                  </li>

                {% endfor %}
                <li class="cart-list-item">
                  <div class="d-flex item-detail">
                    <h5 style="color: #637282;">Total : <span>₹</span> {{ total }}</h4>
                  </div>
                </li>

              </ul>
              <div class="separator-line"></div>
              <h5>Deliver to </h5>

              {% if address | length != 0 %}
                <select  id="mySelect">
                  {% for add in address %}
    
                      {% if loop.index == 1 %}
                        <option value="{{ add.id }}" selected>{{ add.address_name }}</option>
                      {% else %}
                        <option value="{{ add.id }}">{{ add.address_name }}</option>
                      {% endif %}

                  {% endfor %}
                </select>
                <div class="address-wrapper"></div>
              {% endif %}
                
                <div>
                  <a href="{{ url_for('view.delivery_address') }}">Add new address</a>
                </div>
                <br>
                <h5>Payment Method</h5>
                <div class="payment-method-wrapper">
                  <div id="container"></div>
                  <a class="payment-method" href="{{ url_for('view.payment') }}">debit/credit card</a>
                  <button class="payment-method" href="" id="me" onclick="enableButton2()">Cash on delivery</button>
                </div>

          </div>
          <form action="{{ url_for('view.place_order') }}" method="post">
            <input type="hidden" name="address" id="place_order_address">
            <div class="col-lg-12 text-right checkout-btn mt-16">
              <button type="submit" class="btn btn-fill" id="place_order" onclick="window.location.href='{{ url_for('view.products') }}';">Place Order</button>
          </div>
          </form>
      </div>
  </div>

<script>
/**
 * Define the version of the Google Pay API referenced when creating your
 * configuration
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/request-objects#PaymentDataRequest|apiVersion in PaymentDataRequest}
 */
const baseRequest = {
  apiVersion: 2,
  apiVersionMinor: 0
};

/**
 * Card networks supported by your site and your gateway
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/request-objects#CardParameters|CardParameters}
 * @todo confirm card networks supported by your site and gateway
 */
const allowedCardNetworks = ["AMEX", "DISCOVER", "INTERAC", "JCB", "MASTERCARD", "VISA"];

/**
 * Card authentication methods supported by your site and your gateway
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/request-objects#CardParameters|CardParameters}
 * @todo confirm your processor supports Android device tokens for your
 * supported card networks
 */
const allowedCardAuthMethods = ["PAN_ONLY", "CRYPTOGRAM_3DS"];

/**
 * Identify your gateway and your site's gateway merchant identifier
 *
 * The Google Pay API response will return an encrypted payment method capable
 * of being charged by a supported gateway after payer authorization
 *
 * @todo check with your gateway on the parameters to pass
 * @see {@link https://developers.google.com/pay/api/web/reference/request-objects#gateway|PaymentMethodTokenizationSpecification}
 */
const tokenizationSpecification = {
  type: 'PAYMENT_GATEWAY',
  parameters: {
    'gateway': 'example',
    'gatewayMerchantId': 'exampleGatewayMerchantId'
  }
};

/**
 * Describe your site's support for the CARD payment method and its required
 * fields
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/request-objects#CardParameters|CardParameters}
 */
const baseCardPaymentMethod = {
  type: 'CARD',
  parameters: {
    allowedAuthMethods: allowedCardAuthMethods,
    allowedCardNetworks: allowedCardNetworks
  }
};

/**
 * Describe your site's support for the CARD payment method including optional
 * fields
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/request-objects#CardParameters|CardParameters}
 */
const cardPaymentMethod = Object.assign(
  {},
  baseCardPaymentMethod,
  {
    tokenizationSpecification: tokenizationSpecification
  }
);

/**
 * An initialized google.payments.api.PaymentsClient object or null if not yet set
 *
 * @see {@link getGooglePaymentsClient}
 */
let paymentsClient = null;

/**
 * Configure your site's support for payment methods supported by the Google Pay
 * API.
 *
 * Each member of allowedPaymentMethods should contain only the required fields,
 * allowing reuse of this base request when determining a viewer's ability
 * to pay and later requesting a supported payment method
 *
 * @returns {object} Google Pay API version, payment methods supported by the site
 */
function getGoogleIsReadyToPayRequest() {
  return Object.assign(
      {},
      baseRequest,
      {
        allowedPaymentMethods: [baseCardPaymentMethod]
      }
  );
}

/**
 * Configure support for the Google Pay API
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/request-objects#PaymentDataRequest|PaymentDataRequest}
 * @returns {object} PaymentDataRequest fields
 */
function getGooglePaymentDataRequest() {
  const paymentDataRequest = Object.assign({}, baseRequest);
  paymentDataRequest.allowedPaymentMethods = [cardPaymentMethod];
  paymentDataRequest.transactionInfo = getGoogleTransactionInfo();
  paymentDataRequest.merchantInfo = {
    // @todo a merchant ID is available for a production environment after approval by Google
    // See {@link https://developers.google.com/pay/api/web/guides/test-and-deploy/integration-checklist|Integration checklist}
    // merchantId: '12345678901234567890',
    merchantName: 'Example Merchant'
  };
  return paymentDataRequest;
}

/**
 * Return an active PaymentsClient or initialize
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/client#PaymentsClient|PaymentsClient constructor}
 * @returns {google.payments.api.PaymentsClient} Google Pay API client
 */
function getGooglePaymentsClient() {
  if ( paymentsClient === null ) {
    paymentsClient = new google.payments.api.PaymentsClient({environment: 'TEST'});
  }
  return paymentsClient;
}

/**
 * Initialize Google PaymentsClient after Google-hosted JavaScript has loaded
 *
 * Display a Google Pay payment button after confirmation of the viewer's
 * ability to pay.
 */
function onGooglePayLoaded() {
  const paymentsClient = getGooglePaymentsClient();
  paymentsClient.isReadyToPay(getGoogleIsReadyToPayRequest())
      .then(function(response) {
        if (response.result) {
          addGooglePayButton();
          // @todo prefetch payment data to improve performance after confirming site functionality
          // prefetchGooglePaymentData();
        }
      })
      .catch(function(err) {
        // show error in developer console for debugging
        console.error(err);
      });
}

/**
 * Add a Google Pay purchase button alongside an existing checkout button
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/request-objects#ButtonOptions|Button options}
 * @see {@link https://developers.google.com/pay/api/web/guides/brand-guidelines|Google Pay brand guidelines}
 */
function addGooglePayButton() {
  const paymentsClient = getGooglePaymentsClient();
  const button =
      paymentsClient.createButton({onClick: onGooglePaymentButtonClicked});
  document.getElementById('container').appendChild(button);
}

/**
 * Provide Google Pay API with a payment amount, currency, and amount status
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/request-objects#TransactionInfo|TransactionInfo}
 * @returns {object} transaction info, suitable for use as transactionInfo property of PaymentDataRequest
 */
function getGoogleTransactionInfo() {
  return {
    countryCode: 'US',
    currencyCode: 'USD',
    totalPriceStatus: 'FINAL',
    // set to cart total
    totalPrice: '1.00'
  };
}

/**
 * Prefetch payment data to improve performance
 *
 * @see {@link https://developers.google.com/pay/api/web/reference/client#prefetchPaymentData|prefetchPaymentData()}
 */
function prefetchGooglePaymentData() {
  const paymentDataRequest = getGooglePaymentDataRequest();
  // transactionInfo must be set but does not affect cache
  paymentDataRequest.transactionInfo = {
    totalPriceStatus: 'NOT_CURRENTLY_KNOWN',
    currencyCode: 'USD'
  };
  const paymentsClient = getGooglePaymentsClient();
  paymentsClient.prefetchPaymentData(paymentDataRequest);
}

/**
 * Show Google Pay payment sheet when Google Pay payment button is clicked
 */
function onGooglePaymentButtonClicked() {
  const paymentDataRequest = getGooglePaymentDataRequest();
  paymentDataRequest.transactionInfo = getGoogleTransactionInfo();

  const paymentsClient = getGooglePaymentsClient();
  paymentsClient.loadPaymentData(paymentDataRequest)
      .then(function(paymentData) {
        // handle the response
        processPayment(paymentData);
      })
      .catch(function(err) {
        // show error in developer console for debugging
        console.error(err);
      });
}
/**
 * Process payment data returned by the Google Pay API
 *
 * @param {object} paymentData response from Google Pay API after user approves payment
 * @see {@link https://developers.google.com/pay/api/web/reference/response-objects#PaymentData|PaymentData object reference}
 */
function processPayment(paymentData) {
  // show returned data in developer console for debugging
    console.log(paymentData);
  // @todo pass payment token to your gateway to process payment
  paymentToken = paymentData.paymentMethodData.tokenizationData.token;
}</script>
<script async
  src="https://pay.google.com/gp/p/js/pay.js"
  onload="onGooglePayLoaded()"></script>  

<script>
  $('#mySelect').on('change', function(e) {
    myFunction($(this).val());
  });

  $(document).on("ready", function (e) {

    var value = $('#mySelect').val();
    myFunction(value);
  });

  function enableButton2() {
    document.getElementById("me").style.background = '#00BCD6';
    document.getElementById("me").style.color = 'white';

  }

  function myFunction(value) {
    var name = {{ data|safe }};
      for (y in name) {
        if (name[y]['address_id'] == value) {
            
          document.getElementById("place_order_address").value = value
            var data = `
            <div class="name">
                    ${name[y]['first_name']} ${name[y]['last_name']}
            </div>
            <div class="email">
              ${name[y]['email']}
            </div>
            <div class="mobile">
              ${name[y]['phone_number']}
            </div>
             <div class="address">
                ${name[y]['address']}, ${name[y]['city']}, ${name[y]['state']}, ${name[y]['postal_code']}
            </div>
            <div clas="actions">
              <a href="/edit_address/${value}">Edit address</a>
            </dv>
            `;
            name[y]['first_name']+' '+name[y]['last_name']+"<br/>"+
            name[y]['email'] +"<br/>"+
            name[y]['phone_number'] +"<br/>"+
            name[y]['address']+' '+name[y]['city']+' '+name[y]['state']+' '+name[y]['postal_code'];

            $('.address-wrapper').empty();
            $('.address-wrapper').html(data);
          // document.getElementById("edit_stuff").href = "/edit_address/"+ name[y]['address_id']
          // document.getElementById("edit_stuff").style = "visibility: visible;"
        }
      }
    
  }
</script>
{% endblock %}

src/templates/checkout.html
{% extends "layout.html" %}

{% block content %}

<div class="container single-product-content bg-color-white pt-15px pb-20px">
  <form method="post" action="{{ url_for('view.add_address') }}">

    <div class="row">
    <div class="form-group col-12">
      <label>Address Name</label>
      <input type="text" class="form-control" value="Address({{ address_count }})" name="address_name" required>
    </div>

    <div class="form-group col-6">
      <label>First Name</label>
      <input type="text" class="form-control" name="first_name" required>
    </div>

    <div class="form-group col-6">
      <label>Last Name</label>
      <input type="text" class="form-control" name="last_name" required >
    </div>
    
    <div class="form-group col-6">
      <label>Email</label>
      <input type="email" class="form-control" name="email">
    </div>

    <div class="form-group col-6">
      <label>Phone Number</label>
      <input type="number" class="form-control" name="phone_number" required>
    </div>

    <div class="form-group col-12">
      <label>Address</label>
      <textarea name="address" class="form-control" rows="3" required></textarea>
    </div>
    
    <div class="form-group col-6">
      <label>Country</label>
      <input list="countries" class="form-control" name="country" required>
      <datalist id="countries">
        <option value="India">
        <option value="Canada">
        <option value="U.S">
      </datalist>
    </div>
    
    <div class="form-group col-6">
      <label>State</label>
      <input list="states" class="form-control" name="state" required>
      <datalist id="states">
        <option value="Gujarat">
        <option value="Rajsthan">
        <option value="Maharashtra">
      </datalist>
    </div>
    
    <div class="form-group col-6">
      <label>City</label>
      <input list="cities" class="form-control" name="city" required>
      <datalist id="cities">
        <option value="Ahmedabad">
        <option value="Gandhinagar">
        <option value="Junaghadh">
      </datalist>
    </div>
    
    <div class="form-group col-6">
      <label>Postal Code</label>
      <input type="text" class="form-control" name="postal_code" required>
    </div>

    <div class="col-12 text-right">
      <button class="btn btn-fill" type="submit">Add</button>
    </div>
    
  </div>
  </form>
 
</div>

{% endblock %}

src/templates/orders.html
{% extends "layout.html" %}

{% block content %}

  <div class="container single-product-content bg-color-white pt-15px pb-20px">
      <h5>Order History</h5>
      <div class="row">
          <div class="col-lg-12">

              <ul class="product-images-gallery">
                
                {% for cart in cart_list %}
                  <li class="cart-list-item">
                      <div class="d-flex item-detail">
                        <a href="{{ url_for('view.product', id=cart[1].id) }}">
                          <img src="{{ url_for('static', filename='assets/images/products/') }}{{ cart[2].image_url }}" 
                          alt="Product image" width="150" height="150">
                        </a>
                          <div class="single-product-des pt-0">
                              <h5 class="product-title pb-0">{{ cart[1].name }}</h5>
                              <div class="quantity d-flex m-0">
                                  <div class="ml-15px mb-0 single-product-price"><span>₹</span> <strong id="product_price">{{ cart[1].price }}</strong></div>
                              </div>
                          </div>
                        <div><p>{{ cart[0].status }}</p></div>
                      </div>
                      <div class="separator-line"></div>
                  </li>

                {% endfor %}
             

              </ul>    
          </div>
      </div>
  </div>
  

{% endblock %}

src/templates/shop-right-sidebar.html
{% extends "layout.html" %}

{% block content %}
  <div class="page_main_title mb-60px">
      <div class="container">
          <div class="row align-items-center">
              <div class="col-lg-6 text-center text-lg-left">
                  <h4>All Products</h4>
              </div>
              <div class="col-lg-6">
                  <div class="breadcrumbs mt-10px mt-lg-0 text-center text-lg-right">
                      <span class="first-item">
                          <a href="{{ url_for('view.products') }}">HOME</a>
                      </span>
                      <span class="separator">/</span>

                      <span class="last-item"><a href="{{ url_for('view.products') }}">All Products</a></span>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Products -->
  <div class="container">
      <div class="row">
          <div class="col-lg-9">
              <div class="shop-item-toolbar">

                  <!-- <div class="items-ordering">
                      <select name="orderby" class="orderby">
                          <option value="menu_order" selected="selected">Default sorting</option>
                          <option value="price">Sort by price: low to high</option>
                          <option value="price-desc">Sort by price: high to low</option>
                      </select>
                  </div> -->
              </div>
          </div>
          <div class="col-lg-9">
              <ul class="row products">
                  {% for product in products %}
                  <li class="product col-6 col-md-4 col-lg-4">
                      <div class="product-img-wrapper">
                          <a href="{{ url_for('view.product', id=product[0].id) }}">
                              <img width="430" height="480" src="{{ url_for('static', filename='assets/images/products/') }}{{ product[1].image_url }}" alt="Product image">
                          </a>
                          <a rel="nofollow" href="{{ url_for('view.add_to_cart', product_id=product[0].id) }}" class="btn btn-dark rounded-0 btn-add-to-cart">Add
                              to cart</a>
                      </div>
                      <div class="product-white-wrapper align-items-center">
                          <h6 class="product-title">
                              <a href="{{ url_for('view.product', id=product[0].id) }}"> {{ product[0].name }}</a>
                          </h6>
                          <span class="price">
                              <span class="amount">
                                  <span class="currencySymbol">₹</span> {{ product[0].price }}</span>
                          </span>
                    
                      </div>
                  </li>
                  {% endfor %}
              </ul>
              <nav class="pagination_holder">
                  <ul class="pagination mb-60px">
                      <li class="page-item active">
                          <a class="page-link" href="#">1</a>
                      </li>
                      <li class="page-item">
                          <a class="page-link" href="#">2</a>
                      </li>
                      <li class="page-item">
                          <a class="page-link" href="#">3</a>
                      </li>
                      <li class="page-item">
                          <a class="page-link" href="#">4</a>
                      </li>
                      <li class="page-item">
                          <a class="page-link" href="#" aria-label="Next">
                              <span class="">></span>
                          </a>
                      </li>
                  </ul>
              </nav>
          </div>
          <div class="col-lg-3 sidebar">
              <div class="bg-color-grayflame widget pt-30px pb-30px px-30px">
                  <h5 class="widget-title">Categories</h5>
                  <ul class="category-list list-unstyled">
                      {% for category in categories %}
                      <li>
                          <a href="{{ url_for('view.products_by_category', category_id=category.id) }}">
                              {{ category.name }}
                          </a>
                      </li>
                      {% endfor %}
                  </ul>
              </div>
          </div>
      </div>
  </div>
{% endblock %}